### ISSUE TITLE
USER STORY Sign up for a new account

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#1]
As a **User** I can **sign up for a new user account** so that **I can have complete functionality of the whole store**

**Acceptance Criteria:**
•	1. A sign-up link is clearly shown in the nav bar
•	2. The user can easily enter all required details in form, name, email, password
•	3. Form validation, the form won't submit if it is not filled out correctly

**Tasks:**

- [x] Task 1. Install allauth,
- [x] Task 2. configure URLs, add to settings.py, run final migrations
- [x] Task 3. Set up URL link in nav bar
