### ISSUE TITLE
USER STORY Follow Stores Social Media Accounts

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#10]
As a **Shopper** I can **easily find the store's social media accounts** so that  **so I can follow them and find out more about the store**

**Acceptance Criteria:**
•	1. Shoppers can easily find out Facebook business page, and our social channels. And follow us
•	2.
•	3.

**Tasks:**

- [x] Task 1. Social media icons are prominent in the base.html footer
- [x] Task 2. The social media page opens on a new page
- [x] Task 3. Set up a Facebook Business page
