### ISSUE TITLE
USER STORY 404 & 500 Error Page

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#11]
As a **user** I can **get a custom error message displayed** so that **if something is not working or an error occurs on the website**

**Acceptance Criteria:**
•	1. Users get a custom error message displayed if a 404 or 500 error occurs

**Tasks:**

- [x] Task 1. Set up views
- [x] Task 2. Create HTML and CSS for pages
- [x] Task 3. Test different errors so see if pages are displayed
