### ISSUE TITLE
USER STORY On Site SEO

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#13]
As a site **Admin** I can **use onsite SEO and keywords** so that **my website will rank in search engines for relevant keywords and drive traffic to my site**

**Acceptance Criteria:**
•	1. There are keywords in the head of the HTML page and in the content of the site.
•	2. Relevant keywords are chosen that are low in competition and high in traffic.

**Tasks:**

- [x] Task 1. Keyword research
- [x] Task 2. Analyze and select relevant keywords that relate to the site niche, that are low in competition, and that has good traffic.
- [x] Task 3. Put keywords into head elements and content of the site
