### ISSUE TITLE
USER STORY Web Marketing

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#14]
As **Admin** I can **leverage web marketing** to drive **website traffic, increase sales, and build brand awareness and customer retention**

**Acceptance Criteria:**
•	1. Newsletter sign-up integration and set up in Mailchimp, set up marketing campaigns at a later date.
•	2. Social media, leveraging followers on social channels to increase sales and brand awareness
•	3. Blog, content marketing using targeted keywords and educating customers about products by using blog posts.

**Tasks:**

- [x] Task 1. Integrate mail chimp in the newsletter sign-up form and set up a marketing campaign for subscribers
- [x] Task 2. Set up and optimize the Facebook page and plan content calendar, and consider paid ads
- [x] Task 3. Create blog posts and content creeation calendar, and optimize with SEO keywords
