### ISSUE TITLE
USER STORY Privacy Policy

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#18]
As a **User** I can **view the privacy policy** so that **I can see it the website is credible and trustworthy**

**Acceptance Criteria:**
•	1. A privacy policy link is visible in the footer so the user can read the policy

**Tasks:**

- [x] Task 1. Generate a privacy policy using a privacy policy generator
- [x] Task 2. Create a link in the base.html footer
- [x] Task 3. Test to see if it opens ina new page
