### ISSUE TITLE
USER STORY Log In

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#2]
As a returning **User** I can **quickly log in to my account** so that **i can vire my profile, history of past orders, or leave a review**

**Acceptance Criteria:**
•	1. Login displayed in nav bar so user can quickly access the login page
•	2. The log-in page displays fields so the user can log into the account previously registered.
•	3.

**Tasks:**

- [x] Task 1. Configure all auth, as discussed previously(in registering the account)
- [x] Task 2. Login link in the nav bar
- [x] Task 3. Styling for log-in page
