### ISSUE TITLE
USER STORY View Individual Product Details

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#20]
As a **Shopper** I can **view individual product details** so that **I can read the product descriptions and see if I want to buy the product**

**Acceptance Criteria:**
•	1. User can click on the product image/link and is brought to a single page all about the product

**Tasks:**

- [x] Task 1. Create view
- [x] Task 2.Create a product HTML page
- [x] Task 3.Wire up URLs and links
