### ISSUE TITLE
USER STORY Make Payments

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#23]
As a **Shopper** I can **make payments easily & safely** so that **I can pay for my purchase**

**Acceptance Criteria:**
•	1. Users can easily and quickly enter payment details.
•	2. Users feel that their payment is secure

**Tasks:**

- [x] Task 1. Integrate stripe payments at checkout,
- [x] Task 2. Create and style checkout template,
- [x] Task 3. Set up stripe webhooks to handle payments,
- [x] Task 4. Set up webhooks to handle errors.
