### ISSUE TITLE
USER STORY Add product to shopping bag

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#24]
As a **Shopper** I can **add a product to the cart** so that **so that I can buy it later**

**Acceptance Criteria:**
•	1. On the product detail page, the user can click on add to bag button and it will add the selected item to the shopping bag.

**Tasks:**

- [x] Task 1. Create Bag App
- [x] Task 2. Create views
- [x] Task 3. Create a bag.html template,
- [x] Task 4. set up urls
