### ISSUE TITLE
USER STORY View items in bag

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#26]
As a **shopper** I can **view all the items in the shopping bag** so that **so I can confirm that I have all the correct products before checkout**

**Acceptance Criteria:**
•	1. Users can click on the shopping bag and will be brought to a page that shows all the items in the bag.
•	2. If no items are in the bag users have a message no items have been added, with a button to return to the shop

**Tasks:**

- [x] Task 1. Update bag link in the header to link to cart page
- [x] Task 2. Add delivery threshold to settings.py 
- [x] Task 3. Add message if no items in cart and links
- [x] Task 4. Edit css
