### ISSUE TITLE
USER STORY Send Purchase email confirmation

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#27]
As a **shopper** I want **a confirmation email of my order** so that **so I have a record of what I bought**

**Acceptance Criteria:**
•	1. The user receives a confirmation email if the purchase was successful
•	2.
•	3.

**Tasks:**

- [x] Task 1. Create .txt files with email content
- [x] Task 2. wire up the webhook handler to send an email if the order is successful 
- [x] Task 3. add email to setting.py
