### ISSUE TITLE
USER STORY Blog for Content Marketing

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#28]
As an **Admin** I can **post relevant informative content on a blog** so that **I can educate customers, build brand awareness, and leverage SEO keywords**

**Acceptance Criteria:**
•	1. A blog that displays detailed posts so the shopper can learn more about our products with important SEO keywords included

**Tasks:**

- [x] Task 1. Create a blog app
- [x] Task 2. Create Model
- [x] Task 3. Creat Views
- [x] Task 4. Create blog HTML.template
- [x] Task 5. Wire up urls
