### ISSUE TITLE
USER STORY Receive an email to complete registration 

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#4]
As a **User** I can **receive an email from the shop** so that **the user can verify my information and confirm my registration was successful**

**Acceptance Criteria:**
•	1. An email is sent to the user after the user has registered a new account.
•       2. The user clicks on the link to verify thier email address.

**Tasks:**

- [x] Task 1. Add  email host address to Heroku config vars
- [x] Task 2. Update settings.py
- [x] Task 3. Check once deployed to see if emails are working
