### ISSUE TITLE
USER STORY User Profile

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#5]
As a **Registered User** I will have **my own personal profile**  so that  **the user view order history, and update delivery information**

**Acceptance Criteria:**
•	1. Users can access their personal profile from the nav bar
•	2. The profile contains their order history and delivery details
•	3. Delivery details can be updated

**Tasks:**

- [x] Task 1. Set up a new app called profile
- [x] Task 2. Create model, views, and base HTML for the profile page
- [x] Task 3. wire up URLs
