### ISSUE TITLE
USER STORY Contact Us Page

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#6]
As a **Shopper** I would like to **be able to contact the site owner** so that **I can ask questions about products or get  information about delivery**

**Acceptance Criteria:**
•	1. The shopper can easily find and click on the contact us form.
•	2. The shopper can fill out the form with a message to send to the owner.

**Tasks:**

- [x] Task 1. Create a new app contact
- [x] Task 2.Creat model, views & base template
- [x] Task 3. Wire up URLs and test, with a success message
