### ISSUE TITLE
USER STORY Site Purpose

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#7]
As a new **user** I can **quickly find out what this site is about and what it can do for me** so that **I can decide whether I want to buy any products**

**Acceptance Criteria:**
•	1. Easy to Navigate site that gives the user a clear path
•	2. Engaging landing page imagery that tells users straight away what this site is about
•	3. Testimonials are displayed on the homepage to build trust with new users

**Tasks:**

- [x] Task 1. Create index.html and a base HTML templates
- [x] Task 2. Add CSS styling,imagery & content
- [x] Task 3. Test in lighthouse and get user feedback
