### ISSUE TITLE
USER STORY Subscribe to Newsletter

### ISSUE THREAD

**Issue by wlillisdev** [wlillisdev/tasty_tipples#9]
As a **User** I can **sign up to the newsletter** so that **I can find out about new products, special offers or find out more about the company**

**Acceptance Criteria:**
•	1. Users can easily find the signup to newsletter form on all pages of the site
•	2. The form captures users' details and gives them a success message

**Tasks:**

- [x] Task 1. Sign up to MailChimp
- [x] Task 2.Integrate MailChimp JS and CSS files in the base.html
- [x] Task 3. Test form, if working ok on front end and backend
